lepture/flask-oauthlib

flask_oauthlib/provider/oauth2.py, tests/oauth2/server.py, tests/oauth2/test_oauth2.py
Fixes #172
This puts HEAD requests on the same code path as GET in `OAuth2Provider.authorize_handler()`. Effectively, this means that the request parameters will be parsed and validated the same way and passed onto the flask view function.
This behavior is prerequisite for those who want to follow RFC2616 sec 9.4:
> The HEAD method is identical to GET except that the server MUST NOT 
> return a message-body in the response.
=> Make OAuth2 authorize_handler support HTTP HEAD the same way as GET

flask_oauthlib/client.py
When creating an OAuthRemoteApp object with a specific dict of "request_token_params", and afterwards calling make_client() with a specific token as an argument (for instance when calling any of the REST methods which in turn call request()), then "request_token_params" will be added the "resource_owner_key" and "resource_owner_secret" keys and values retrieved from the token passed.
Thus, if you want to call again the authorize() method, a new client will be created that will take as argument the "request_token_params" modified dict (see https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/client.py#L342, https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/client.py#L350).
This has happened to cause "OAuthException: Failed to generate request token" …
=> Don't modify instance attributes when calling make_client with a token

flask_oauthlib/contrib/client/application.py
If no compliance_fixes were passed, the `compliance_fixes.startswith('.')` guard would always raise a NoneType exception, since the `compliance_fixes` property would evaluate to `None`.
=> Fix compliance_fixes not being correctly checked

flask_oauthlib/contrib/client/application.py, flask_oauthlib/contrib/client/signals.py, setup.py
- Using querystring passed `oauth_token` instead of the session stashed one, because storing request token and request token secret in cookie is nonstandard and insecure.
- Fixing the wrong dictionary schema accepted by `make_client` method.
- Adding `request_token_fetched` signal to allow people inspect the request token.
@lepture plz review, thx.
=> Refactor the experiment OAuth 1.0a client.

flask_oauthlib/contrib/client/application.py
The contrib client joins a list of scope with a comma which is wrong.
[RFC6749 section 3.3](https://tools.ietf.org/html/rfc6749#section-3.3) specifies the scopes must be
> expressed as a list of space-delimited, case-sensitive strings.
Processing the scope at this point is also not necessary as the scope
are passed to [requests-oauthlib](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L120-L124) and then [oauthlib](https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/parameters.py#L75-L76) which can [handle a
Python list](https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/utils.py#L23-L32) just fine.
This is also more consistent with the OAuth2 client which [passes the
scope directly to …
=> Remove incorrect handling of scope

flask_oauthlib/provider/oauth2.py
Grant type is allowed if it is part of the 'allowed_grant_types'
of the selected client or if it is one of the default grant types
=> Fix a bug in validate_grant_type

flask_oauthlib/client.py
User can specify additional headers given to the access_token_url HTTP request.
Rationale: This patch allows me to pass the HTTP 'Authentification'
header to Bitbucket that requires basic access authentification for
the access token method.
=> OAuthRemoteApp: new access_token_headers parameter

flask_oauthlib/provider/oauth2.py
The client MAY omit the parameter if the client secret is an empty string. So it need to check the client_secret.
=> [Fix Bug] When library call authenticate_client but client's secret key is null that can cause the program raise a 500 Internal Server Error.

flask_oauthlib/provider/oauth2.py, tests/oauth2/test_oauth2.py, tests/test_oauth2/test_code.py
currently we'd get a 500 Internal Error if we pass an invalid `redirect_uri` to the /authorized view. Here's the backtrace, we can find that there's a ValueError from oauthlib escaped without any catch.
```
217   File "/data/apps/clouda_oauth2/parts/flask-oauthlib/flask_oauthlib/provider/oauth2.py", line 387, in decorated
218     uri, http_method, body, headers
219   File "/data/apps/clouda_oauth2/eggs/oauthlib-0.7.2-py2.7.egg/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
220     return f(endpoint, uri, *args, **kwargs)
221   File "/data/apps/clouda_oauth2/eggs/oauthlib-0.7.2-py2.7.egg/oauthlib/oauth2/rfc6749/endpoints/authorization.py", line 110, in validate_authorization_request
222     uri, http_method=http_method, body=body, headers=headers)
223   File …
```
=> catch Exception in oauth2.py

example/twitter.py
this pull request related to #276, instead of showing redacted message, it will print out original error message when HTTP 403 found.
=> show original error message 

docs/oauth2.rst
Adds a link to the github test folder for the OAuth2 server example. The information there appears to be a lot more up to date than those in the mentioned resources.
=> Updated OAuth2 example links in oauth2.rst

flask_oauthlib/provider/oauth2.py
This pull requests adds traceback logging to all 'except' blocks. This is especially important in an "except Exception" block, as it can catch any exception from any source and for any reason. As a concrete example, in our case a HTML Jinja template filter tried to generate a thumbnail, and failed with an IOError exception, which was subsequently swallowed by Flask-OAuthLib.
Furthermore, I changed the log level from debug to warning in one "except Exception" block, as exceptions caught by such a broad exception handler should not go unnoticed.
=> Log exception traceback.

example/github.py
First, thanks for the library!
I don't see a way for the `authorized_response` method to ever return `None`. Regardless, it seems possible that the response could be something other than `None` like an `OAuthException` so checking for only `None` seem insufficient.
This change fixes the situation where `authorized_response` returns something other than `None` but there is no `access_token` in the response.  I've been seeing this fail on my app with a `KeyError` on line 51.  So, I'm currently losing the real error from github which could explain *why* the `access_token` is missing.
Am I missing something?
=> Improve handling of github authorization error

flask_oauthlib/provider/oauth2.py, flask_oauthlib/utils.py, tests/_base.py, tests/oauth2/test_oauth2.py, tests/test_oauth2/test_client_credential.py, tests/test_oauth2/test_code.py, tests/test_oauth2/test_refresh.py
*This PR closes #132 and #199*
Section 4.1.3 says "If the client type is confidential or the client was
issued client credentials (or assigned other authentication
requirements), the client MUST authenticate with the authorization
server as described in Section 3.2.1.", and that is HTTP Basic
Authentication.
This commit is based on #292 PR.
@night I have refactored your PR #292 (`request.client_id` and `request.client_secret` are not patched in `_get_client_creds_from_reponse` anymore) and fixed Python 3.x compatibility issues.
=> Handle HTTP Basic Auth for client's access to token endpoint

flask_oauthlib/provider/oauth2.py, tests/oauth2/server.py, tests/oauth2/test_oauth2.py
It should be possible to have valid access tokens that doesn't have an
expiration date set. The OAuth RFC recommends having it, but it's not a
requirement. We therefore should only validate expiration date on bearer
token if it's set.
Ref:
https://tools.ietf.org/html/rfc6749#section-4.2.2
https://tools.ietf.org/html/rfc6749#section-5.1
=> Allow having access tokens without expiration date

tests/oauth2/server.py
Update the `SQLAlchemy` import from `flask_sqlalchemy` to avoid deprecation warnings:
```
Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
```
=> Fix deprecated SQLAlchemy import to avoid warning

flask_oauthlib/provider/oauth2.py
Remove a `except Exception as e:` which will catch all exception in the view function, add `stack_info=True` to other loggers.
=> fix #277, bad exception handle

flask_oauthlib/client.py, tests/test_client.py
In the simple use cases, people may only need the access_token, making a tuple/list or dictionary may be excess. With this pr, we can just get the value of `access_token` as a string. Then we can pass it to `request()` method or save it in the database directly. For example:
```python
@app.route('/login/authorized')
def authorized():
resp = remote.authorized_response()
access_token = resp['access_token']
remote.get('user', token=access_token)
user = User(access_token=access_token)  # store into database
user.save()
```
Maybe add an `access_token` parameter same with OAuthlib’s [`Client.access_token`](https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/clients/base.py#L53) is more clear, but for now, I think we can just add an internal support.
=> Add support for string type token

flask_oauthlib/provider/oauth2.py, tests/oauth2/test_oauth2.py
Changes: Along with "error", "state" is also passed to redirect_uri if it's present on client request.
* Expected behavior: on access_denied, the redirect_uri should be called with error and state if state is present on request
* Actual behavior: only error is passed to redirect_uri and state is always lost.
The PR fixes the bug and make it standard compliant.
Quote from RFC 6749 (https://tools.ietf.org/html/rfc6749#section-4.1.2): 
>    state
REQUIRED if a "state" parameter was present in the client
authorization request.  The exact value received from the
client.
=> Bug fix: Preserve "state" parameter in the oauth2 handler when non-critical errors happen as required in RFC 6749.

setup.py
1.2.0 requires oauthlib 3, which we are not compatible with
=> Pin requests-oauthlib version to <1.2.0

README.rst
Hey
We recently launched a new page specifically geared towards developers on auth0.com.
Can we change the link in the sponsorship message?
Thanks again for your open-source work!
=> Update Auth0 sponsorship link

docs/oauth1.rst
There is a small typo in docs/oauth1.rst.
Should read `usually` rather than `usally`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, usally -> usually
